// Generated by CoffeeScript 1.6.3
doctype(5);

html({
  lang: 'en'
}, function() {
  head(function() {
    meta({
      charset: 'utf-8'
    });
    meta({
      'http-equiv': 'X-UA-Compatible',
      content: 'ie=edge,chrome=1'
    });
    meta({
      'http-equiv': 'content-type',
      content: 'text/html; charset=utf-8'
    });
    meta({
      name: 'viewport',
      content: 'width=device-width, initial-scale=1'
    });
    text(this.getBlock('meta').toHTML());
    title(this.getPreparedTitle());
    meta({
      name: 'title',
      content: this.getPreparedTitle()
    });
    meta({
      name: 'author',
      content: this.getPreparedAuthor()
    });
    meta({
      name: 'email',
      content: this.getPreparedEmail()
    });
    meta({
      name: 'description',
      content: this.getPreparedDescription()
    });
    meta({
      name: 'keywords',
      content: this.getPreparedKeywords()
    });
    text(this.getBlock('styles').toHTML());
    link({
      rel: 'stylesheet',
      href: '/styles/main.css'
    });
    link({
      rel: 'stylesheet',
      media: 'all and (min-width: 1025px)',
      href: '/styles/desktop.css'
    });
    link({
      rel: 'stylesheet',
      media: 'all and (min-width: 641px) and (max-width: 1024px)',
      href: '/styles/tablet.css'
    });
    return link({
      rel: 'stylesheet',
      media: 'all and (max-width: 640px)',
      href: '/styles/mobile.css'
    });
  });
  return body(function() {
    div('#wrapper', function() {
      header({
        role: 'banner'
      }, function() {
        a({
          href: '/',
          title: this.site.title
        }, function() {
          return img({
            src: '/images/etlogo-color.png',
            alt: 'logo',
            height: '0',
            width: '0'
          });
        });
        nav({
          role: 'navigation'
        }, function() {
          return ul(function() {
            var cssname, documentMatch, page, pageMatch, _i, _len, _ref, _results;
            _ref = this.getCollection('pages').toJSON();
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              page = _ref[_i];
              pageMatch = page.match || page.url;
              documentMatch = this.document.match || this.document.url;
              cssname = documentMatch.indexOf(pageMatch) === 0 ? 'menu-current' : 'not-menu-current';
              _results.push(li({
                'id': cssname
              }, function() {
                return a({
                  href: page.url,
                  title: page.title
                }, page.title);
              }));
            }
            return _results;
          });
        });
        return div('#social-icons', function() {
          a({
            href: 'https://github.com/Greduan',
            title: 'GitHub - Greduan'
          }, function() {
            return span('.icon-github-squared', '');
          });
          a({
            href: 'https://www.gittip.com/Greduan',
            title: 'Gittip - Greduan'
          }, function() {
            return span('.icon-gittip', '');
          });
          a({
            href: 'https://bitbucket.org/Greduan',
            title: 'BitBucket - Greduan'
          }, function() {
            return span('.icon-bitbucket-squared', '');
          });
          a({
            href: 'http://stackoverflow.com/users/1622940/eduan',
            title: 'StackOverflow - Greduan'
          }, function() {
            return span('.icon-stackoverflow', '');
          });
          a({
            href: 'https://plus.google.com/u/0/101160916170411335097/',
            title: 'Eduan Lávaque (Eduan) - Google+'
          }, function() {
            return span('.icon-gplus-squared', '');
          });
          a({
            href: 'http://www.youtube.com/user/eduantech',
            title: 'Eduan Lávaque - YouTube'
          }, function() {
            return span('.icon-youtube-squared', '');
          });
          return a({
            href: 'http://steamcommunity.com/id/greduan/',
            title: 'Steam Community - Greduan'
          }, function() {
            return span('.icon-steam', '');
          });
        });
      });
      main({
        role: 'main'
      }, function() {
        return this.content;
      });
      return footer({
        role: 'contentinfo'
      }, function() {
        return div(function() {
          return "<p><a href=\"https://github.com/Greduan/eduantech.docpad/blob/master/LICENSE.md\" title=\"License Terms\">License Terms</a> | Powered by <a href=\"http://docpad.org/\">DocPad</a> and <a href=\"http://realiseweb.nl\">Realiseweb</a>.</p>";
        });
      });
    });
    text(this.getBlock('scripts').toHTML());
    script({
      src: '/scripts/jquery-1.10.1.min.js'
    });
    script({
      src: '/scripts/modernizr.js'
    });
    return script({
      src: '/scripts/main.js'
    });
  });
});
