// Generated by CoffeeScript 1.6.3
doctype(5);

html({
  lang: 'en'
}, function() {
  head(function() {
    meta({
      charset: 'utf-8'
    });
    meta({
      'http-equiv': 'X-UA-Compatible',
      content: 'ie=edge,chrome=1'
    });
    meta({
      'http-equiv': 'content-type',
      content: 'text/html; charset=utf-8'
    });
    meta({
      name: 'viewport',
      content: 'width=device-width, initial-scale=1'
    });
    text(this.getBlock('meta').toHTML());
    title(this.getPreparedTitle());
    meta({
      name: 'title',
      content: this.getPreparedTitle()
    });
    meta({
      name: 'author',
      content: this.getPreparedAuthor()
    });
    meta({
      name: 'email',
      content: this.getPreparedEmail()
    });
    meta({
      name: 'description',
      content: this.getPreparedDescription()
    });
    meta({
      name: 'keywords',
      content: this.getPreparedKeywords()
    });
    text(this.getBlock('styles').toHTML());
    link({
      rel: 'stylesheet',
      href: '/styles/main.css'
    });
    link({
      rel: 'stylesheet',
      media: 'all and (min-width: 1025px)',
      href: '/styles/desktop.css'
    });
    link({
      rel: 'stylesheet',
      media: 'all and (min-width: 641px) and (max-width: 1024px)',
      href: '/styles/tablet.css'
    });
    link({
      rel: 'stylesheet',
      media: 'all and (max-width: 640px)',
      href: '/styles/mobile.css'
    });
    return script({
      src: '/scripts/jquery-1.10.1.min.js'
    });
  });
  return body(function() {
    nav('.pushy pushy-left', {
      role: 'navigation'
    }, function() {
      return ul(function() {
        var cssname, documentMatch, page, pageMatch, _i, _len, _ref, _results;
        _ref = this.getCollection('pages').toJSON();
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          page = _ref[_i];
          pageMatch = page.match || page.url;
          documentMatch = this.document.match || this.document.url;
          cssname = documentMatch.indexOf(pageMatch) === 0 ? 'menu-current' : 'not-menu-current';
          _results.push(li({
            'id': cssname
          }, function() {
            return a({
              href: page.url,
              title: page.title
            }, page.title);
          }));
        }
        return _results;
      });
    });
    div('.site-overlay', '');
    div('#wrapper', function() {
      div('.menu-btn', function() {
        return text('&#9776; MENU');
      });
      main({
        role: 'main'
      }, function() {
        return this.content;
      });
      return footer({
        role: 'contentinfo'
      }, function() {
        return div(function() {
          return "<p><a href=\"https://github.com/Greduan/eduantech.docpad/blob/master/LICENSE.md\" title=\"License Terms\">License Terms</a> | Powered by <a href=\"http://docpad.org/\">DocPad</a> and <a href=\"http://realiseweb.nl\">Realiseweb</a>.</p>";
        });
      });
    });
    text(this.getBlock('scripts').toHTML());
    script({
      src: '/scripts/modernizr.js'
    });
    script({
      src: '/scripts/pushy.js'
    });
    return script({
      src: '/scripts/main.js'
    });
  });
});
